### ISSUE TITLE
HOW TO GET ADDRESS NODE IN OUR GRAPH AS LIKE AS ICIJ?

### ISSUE THREAD

**Issue by SaravananKalimuthu21** [Senzing/mapper-ijic#14]
Hi Team,
 
We are working on the Senzing API(/api/entity-networks) to get a data graph visualizer.

We are Mimicing the same data icij provides. https://offshoreleaks.icij.org/pages/database

They have a result for a name Nurali Aliyev here. https://offshoreleaks.icij.org/nodes/12060831. You can able to see the node with an address on the top of it. Refer the image 
![105a_icij_visualizer](https://user-images.githubusercontent.com/48215082/76841657-18793580-685f-11ea-9028-3f33a57ca79f.png)

The same data which is provided by senzing api doesn't have the third node with the address as mentioned in the image 
![105a_our_visualizer](https://user-images.githubusercontent.com/48215082/76841682-22029d80-685f-11ea-8e6b-90f41f4aa741.png)
.

Even the API result(
![Senzing_data](https://user-images.githubusercontent.com/48215082/76841695-27f87e80-685f-11ea-9cd5-7f8b05de3bed.png)
) and the mapper JSON file also didn't have a separate record for that address  @node.

Is there any other modifications needed in the mapper-icij to resolve this?

How can we get the data for that third node from icij-mappers?

Thanks.

**Comment by arawinters** [comment]
this looks like a request to the same /entity-networks endpoint found in the [OAS spec](http://editor.swagger.io/?url=https://raw.githubusercontent.com/Senzing/senzing-rest-api/master/senzing-rest-api.yaml). We use this same endpoint to power graph. Maybe I'm misunderstanding, but are you asking how to get adress data for a resolved entity, or how to map it properly so that the api server returns that info @SaravananKalimuthu21 ?

(see screenshot)
![2020-03-17_072824](https://user-images.githubusercontent.com/13721038/76867032-35dbde80-6822-11ea-91c5-05a1325964d6.png)

**Comment by SaravananKalimuthu21** [comment]
No Ara,

We are expecting one more node to be presented in the graph. That data seems to be missing in the API result.

Can you please compare the images which i uploaded and you can see a node data(marked red) is missing in the API response.

Thanks.

**Comment by jbutcher21** [comment]
In Senzing, addresses are features and can be found in the feature section of the getEntity API call.   You can use the LIB_FEAT_ID as the node_id.  
![image](https://user-images.githubusercontent.com/22121925/76908284-87f22380-6865-11ea-9531-bfbb7f38422f.png)

Other have added a "show features" of a node option that create nodes from features and any entity 
![image](https://user-images.githubusercontent.com/22121925/76908710-9856ce00-6866-11ea-9fd4-27c5b54e149e.png)

And link them across entities ...
![image](https://user-images.githubusercontent.com/22121925/76908756-b1f81580-6866-11ea-99a8-fc411c8c89af.png)

Please let me know if you need any additional information!

**Comment by SaravananKalimuthu21** [comment]
Thank you Jeff,

Let us analyse the data and make sure we can make this work.

Will let you know.

**Comment by SaravananKalimuthu21** [comment]
Jeff,

Thanks for the clarification.

We tried to get that address information and trying to form a separate node with that address.

But we have the LIB_FEAT_ID missing. We need that LIB_FEAT_ID to map the address field properly as a unique link. We have no idea whats restricting this from providing the LIB_FEAT_ID.
![libfeatid](https://user-images.githubusercontent.com/48215082/76962996-471e0b80-6946-11ea-9752-af1bbd831121.png)
![sample](https://user-images.githubusercontent.com/48215082/76963475-17bbce80-6947-11ea-8d41-9071381d43e8.png)

Please clarify us to get that ID in our API response.

Thanks.

**Comment by jbutcher21** [comment]
Ah, you are using the web service api calls.   In that case, just use the primaryValue as the node_id.

Jeff Butcher
Senzing, Chief Architect
jbutcher@senzing.com<mailto:jbutcher@senzing.com>
(702) 205-8424

Follow Senzing on Website<http://www.senzing.com/> | Twitter<https://twitter.com/senzing> | LinkedIn<https://www.linkedin.com/company/senzing-inc/> | Facebook<https://www.facebook.com/senzinginc/>
If you are not an intended recipient of confidential and privileged information in this email, please delete it, notify us immediately at postmaster@senzing.com<mailto:postmaster@senzing.com>, and do not use or disseminate such information.

**Comment by SaravananKalimuthu21** [comment]
Thanks Jeff.

We used primaryValue as a nodeId. It seems to be working.

Will let you know if anything else needed.

You can update this ticket as resolved now.

I have another query, i'll raise another ticket for that.

**Comment by jbutcher21** [comment]
Thanks Saravanan!
